resources:
- ../base/
patchesStrategicMerge:
- |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend
      namespace: test
      labels:
        app.kubernetes.io/name: guestbook
        app.kubernetes.io/component: frontend
